<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>False</UseWindowsForms>
		<SatelliteResourceLanguages>zh-Hans;en</SatelliteResourceLanguages>
		<PublishDir>bin\$(MSBuildProjectName)\</PublishDir>
		<CleanPublishFolder>true</CleanPublishFolder>
		<Title>一个用于 F# 和 WPF 的响应式数据绑定库，提供类型安全且函数式的 UI 绑定解决方案。</Title>
		<Description>System.Reactive &amp; WPF 的响应式数据绑定，F#语言编写</Description>
		<PackageReadmeFile>readme.md</PackageReadmeFile>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<Authors>xp44m</Authors>
		<Company>34696643@qq.com</Company>
		<Copyright>xp44mm</Copyright>
		<PackageLicenseExpression>LGPL-3.0-or-later</PackageLicenseExpression>
        
		<Version>0.1.10</Version>
		<PackageReleaseNotes>UIElement/FrameworkElement</PackageReleaseNotes>
        
		<RepositoryUrl>https://github.com/xp44mm/FSharp.ReactiveWpf</RepositoryUrl>
		<PackageTags>fsharp;reactive;wpf;xaml</PackageTags>
	</PropertyGroup>

	<ItemGroup>
	  <Page Remove="Row.xaml" />
	  <Page Remove="TextBoxWindow.xaml" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Row.xaml" />
		<EmbeddedResource Include="TextBoxWindow.xaml" />
		<Compile Include="XamlLoader.fs" />
		<Compile Include="Internal.fs" />
		<Compile Include="Brushes.fs" />
		<Compile Include="TableCell.fs" />
		<Compile Include="TableRow.fs" />
		<Compile Include="TableRowGroup.fs" />
		<Compile Include="TableColumn.fs" />
		<Compile Include="Table.fs" />
		<Compile Include="Paragraph.fs" />
		<Compile Include="Run.fs" />
		<Compile Include="UIElement.fs" />
		<Compile Include="FrameworkElement.fs" />
		<Compile Include="TextBlock.fs" />
		<Compile Include="TextBox.fs" />
		<Compile Include="NumberBox.fs" />
		<Compile Include="ComboBox.fs" />
		<Compile Include="ToggleButton.fs" />
		<Compile Include="CheckBox.fs" />
		<Compile Include="RadioButton.fs" />
		<Compile Include="Row.fs" />
		<Compile Include="TextBoxWindow.fs" />
		<Compile Include="MediaPlayer.fs" />
		<Compile Include="DependencyObjectUtils.fs" />
		<Compile Include="GreenWhite.fs" />
		<Compile Include="TextFileSaver.fs" />
		<Compile Include="TextFileOpener.fs" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="..\readme.md">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="FSharp.Idioms" Version="1.5.17" />
		<PackageReference Include="MahApps.Metro" Version="2.4.11" />
		<PackageReference Include="System.Reactive" Version="7.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Update="FSharp.Core" Version="10.1.400" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\FSharp.Idioms.Reactive\FSharp.Idioms.Reactive.fsproj" />
	</ItemGroup>
</Project>
